name: Publish Blog Posts

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Download previous tracking data
      uses: actions/download-artifact@v2
      continue-on-error: true
      with:
        name: tracking-data
        path: .tracking

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create output directory
      run: mkdir -p dist
    
    - name: Add scripts to Python path
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$PWD" >> $GITHUB_ENV
    
    - name: Run publication script
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        MARKDOWN_DIR: ./posts
        HTML_OUTPUT_DIR: ./dist
      run: |
        python scripts/publish_posts.py

    - name: Upload tracking data
      uses: actions/upload-artifact@v2
      if: always()  # Upload even if the script fails
      with:
        name: tracking-data
        path: .tracking/
        retention-days: 90  # Keep tracking data for 90 days