name: Publish Blog Posts

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create output directory
      run: mkdir -p dist
    
    - name: Run publication script
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
        MARKDOWN_DIR: ./posts
        HTML_OUTPUT_DIR: ./dist
        PYTHONPATH: ${{ github.workspace }}/scripts
      run: |
        cd scripts
        python publish_posts.py