name: Publish Blog Posts

on:
  push:
    paths:
      - 'posts/*.md'
      - 'posts/images/**'
  schedule:
    - cron: '0 13 * * 2,4'
    - cron: '0 15 * * 6'
  workflow_dispatch:

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directory structure
      shell: bash
      run: |
        # Create all required directories
        mkdir -p scripts/utils
        mkdir -p scripts/config
        mkdir -p dist
        mkdir -p .tracking
        mkdir -p .queue
        
        # Create __init__.py files
        touch __init__.py
        touch scripts/__init__.py
        touch scripts/utils/__init__.py
        touch scripts/config/__init__.py
        
        # Initialize JSON files if they don't exist
        if [ ! -f ".tracking/published_posts.json" ]; then
          echo "{}" > .tracking/published_posts.json
        fi
        
        if [ ! -f ".queue/post_queue.json" ]; then
          echo "{}" > .queue/post_queue.json
        fi
        
        # Set permissions
        chmod -R 755 scripts
        chmod -R 755 dist
        chmod -R 755 .tracking
        chmod -R 755 .queue
        
        # List directory structure for verification
        echo "Directory structure:"
        ls -R
    
    - name: Run publication script
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        MARKDOWN_DIR: ./posts
        HTML_OUTPUT_DIR: ./dist
        PYTHONPATH: ${{ github.workspace }}
      run: python scripts/publish_posts.py
    
    - name: Commit tracking data
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # Add all modified files explicitly
        git add scripts/__init__.py
        git add scripts/convert_markdown.py
        git add scripts/post_tracker.py
        git add scripts/publish_devto.py
        git add scripts/publish_medium.py
        git add scripts/publish_posts.py
        git add scripts/queue_manager.py
        git add scripts/test.py
        git add .tracking/published_posts.json
        git add .queue/post_queue.json
        git status
        # Only commit if there are changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scripts and tracking data [skip ci]" && git push origin HEAD:${GITHUB_REF})
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}