name: Publish Blog Posts

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Initialize tracking directory
      run: |
        mkdir -p .tracking
        echo '{"last_run": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'", "posts": {}}' > .tracking/published_posts.json
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Debug Environment
      run: |
        echo "Current directory structure:"
        ls -R
        echo "\nPython version:"
        python --version
        echo "\nInstalled packages:"
        pip list
        echo "\nTracking file contents:"
        cat .tracking/published_posts.json
    
    - name: Run publication script
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        MARKDOWN_DIR: ./posts
        HTML_OUTPUT_DIR: ./dist
      run: |
        echo "Checking if script exists:"
        ls -l scripts/publish_posts.py
        echo "\nChecking posts directory:"
        ls -l posts/
        echo "\nRunning script with debug output:"
        python -v scripts/publish_posts.py
        
    - name: Upload tracking data
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tracking-data
        path: .tracking/
        retention-days: 90