- name: Create test post
      run: |
        mkdir -p posts
        cat > posts/test-post.md << 'EOF'
        ---
        title: Test Post
        description: This is a test post
        tags: test
        ---

        # Test Post

        This is a test post to verify the publication system is working correctly.

        ## Testing Features

        - Markdown conversion
        - Platform publishing
        - Tracking system
        EOF