name: Publish Blog Posts

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Setup project structure
      run: |
        # Create necessary directories
        mkdir -p scripts/utils scripts/config posts dist logs .tracking
        
        # Create package files
        touch scripts/__init__.py
        touch scripts/utils/__init__.py
        touch scripts/config/__init__.py
        
        # Initialize tracking file
        echo '{"posts": {}}' > .tracking/published_posts.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run publication script
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        MARKDOWN_DIR: ./posts
        HTML_OUTPUT_DIR: ./dist
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # Create wrapper script
        cat > run_publisher.py << 'EOF'
        import sys
        import logging
        from pathlib import Path

        # Configure logging
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler('logs/publish.log'),
                logging.StreamHandler(sys.stdout)
            ]
        )
        
        try:
            from scripts.publish_posts import main
            main()
        except Exception as e:
            logging.error(f"Publication failed: {str(e)}", exc_info=True)
            sys.exit(1)
        EOF
        
        # Run the script
        python run_publisher.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: publish-logs
        path: logs/
        retention-days: 7

    - name: Upload tracking data
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tracking-data
        path: .tracking/
        retention-days: 90