name: Publish Blog Posts

on:
  push:
    paths:
      - 'posts/*.md'
      - 'posts/images/**'
  schedule:
    - cron: '0 13 * * 2,4'
    - cron: '0 15 * * 6'
  workflow_dispatch:

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directory structure
      run: |
        # Create Python package directories
        mkdir -p scripts/utils scripts/config dist .tracking
        touch __init__.py
        touch scripts/__init__.py
        touch scripts/utils/__init__.py
        touch scripts/config/__init__.py
        
        # Initialize tracking files if they don't exist
        [ ! -f ".tracking/published_posts.json" ] && echo "{}" > .tracking/published_posts.json
        [ ! -f ".queue/post_queue.json" ] && mkdir -p .queue && echo "{}" > .queue/post_queue.json
    
    - name: Run publication script
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        MARKDOWN_DIR: ./posts
        HTML_OUTPUT_DIR: ./dist
        PYTHONPATH: ${{ github.workspace }}
      run: python scripts/publish_posts.py
    
    - name: Commit tracking data
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .tracking/published_posts.json .queue/post_queue.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update published posts tracking data [skip ci]"
        git push origin HEAD:${GITHUB_REF}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}